apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-share
provisioner: nfs.csi.k8s.io
parameters:
  server: 84.252.139.202
  share: /nfs-share
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1
