---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_user: vagrant
      ansible_host: 158.160.20.13

vector:
  hosts:
    vector-01:
      ansible_user: vagrant
      ansible_host: 158.160.4.218

lighthouse:
  hosts:
    lighthouse-01:
      ansible_user: vagrant
      ansible_host: 158.160.67.10