---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_user: vagrant
      ansible_password: vagrant
      ansible_host: 192.168.56.11
vector:
  hosts:
    vector-01:
      ansible_user: vagrant
      ansible_password: vagrant
      ansible_host: 192.168.56.11
lighthouse:
  hosts:
    lighthouse-01:
      ansible_user:
      ansible_password:
      ansible_host: